## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras import layers

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition","Department"]]
y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:
# Create a list of at least 10 column names to use as X data

x = [
"Education",
"Age",
"DistanceFromHome",
"JobSatisfaction",
"OverTime",
"StockOptionLevel",
"WorkLifeBalance",
"YearsAtCompany",
"YearsSinceLastPromotion",
"NumCompaniesWorked"]
#print(x)

# Create X_df using your selected columns
X_df = attrition_df[x]

# Show the data types for X_df
X_df.dtypes

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [5]:
X_df["OverTime"] = pd.get_dummies(X_df["OverTime"], drop_first = True, dtype = int).values.reshape(-1,1)

C:\Users\symia\AppData\Local\Temp\ipykernel_24928\1093136357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df["OverTime"] = pd.get_dummies(X_df["OverTime"], drop_first = True, dtype = int).values.reshape(-1,1)

In [6]:
# encoder = OrdinalEncoder()
# X_df["OverTime"] = encoder.fit_transform(X_df[["OverTime"]])

In [7]:
# #is_non_numeric = pd.to_numeric(df['column'], errors='coerce').isnull()
# encoder = OrdinalEncoder(categories=[['No', 'Yes']])
# ['No', 'Yes']]X_df["OverTime"] = encoder.fit_transform(X_df[["OverTime"]])

In [8]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X = X_df
y = y_df
# for i in range(38): #Find the random state that matches the starter code
#     X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=i)
#     print(X_train["OverTime"].value_counts())
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=37)

In [9]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
encoder = OrdinalEncoder()
encoder.fit_transform(X_train[["OverTime"]])
X_train[["OverTime"]] = encoder.fit_transform(X_train[["OverTime"]])
X_test[["OverTime"]] = encoder.fit_transform(X_test[["OverTime"]])

print(X_train[["OverTime"]].value_counts())
print(X_test[["OverTime"]].value_counts())
display(X_train)
display(X_test)

OverTime
0.0         788
1.0         314
Name: count, dtype: int64
OverTime
0.0         266
1.0         102
Name: count, dtype: int64

,Education,Age,DistanceFromHome,JobSatisfaction,OverTime,StockOptionLevel,WorkLifeBalance,YearsAtCompany,YearsSinceLastPromotion,NumCompaniesWorked
1321,4,47,9,3,0.0,0,3,2,2,4
1091,3,33,25,2,0.0,0,3,5,0,1
985,4,31,22,3,1.0,2,2,10,6,1
455,5,33,1,3,0.0,1,3,6,0,4
952,3,31,1,2,1.0,0,4,3,2,1
...,...,...,...,...,...,...,...,...,...,...
437,1,30,7,2,0.0,0,3,3,1,0
988,3,41,22,4,1.0,2,2,6,3,3
251,4,39,2,3,0.0,0,3,19,11,0
844,3,30,10,3,0.0,1,3,10,1,1
363,3,33,5,3,1.0,0,3,1,0,1

,Education,Age,DistanceFromHome,JobSatisfaction,OverTime,StockOptionLevel,WorkLifeBalance,YearsAtCompany,YearsSinceLastPromotion,NumCompaniesWorked
120,3,30,23,3,0.0,3,2,10,0,1
768,3,40,26,1,0.0,1,2,7,7,1
831,3,31,15,3,0.0,1,2,2,2,1
1346,2,45,25,4,0.0,2,2,9,3,0
485,4,27,6,3,0.0,2,2,5,0,0
...,...,...,...,...,...,...,...,...,...,...
376,2,51,14,4,0.0,1,2,7,0,4
1061,2,24,13,2,0.0,1,3,1,0,1
777,3,21,10,1,0.0,0,2,1,1,1
233,4,50,1,4,0.0,1,2,7,0,3
1372,2,39,9,1,0.0,1,3,10,7,1

In [10]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
y_train

     Attrition              Department
1321        No  Research & Development
1091        No  Research & Development
985        Yes  Research & Development
455         No  Research & Development
952        Yes                   Sales
...        ...                     ...
437         No                   Sales
988         No  Research & Development
251         No  Research & Development
844         No                   Sales
363        Yes                   Sales

[1102 rows x 2 columns]

In [12]:
# Create a OneHotEncoder for the Department column
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False, dtype='int')

# Fit the encoder to the training data
ohe.fit(y_train[["Department"]])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dep_encoded = ohe.transform(y_train[["Department"]])
y_test_dep_encoded = ohe.transform(y_test[["Department"]])

# ohe.fit_transform(y_train[["Department"]])
# ohe.fit_transform(y_train[["Department"]])
print([y_train_dep_encoded])
print([y_test_dep_encoded])

[array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])]
[array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0]])]

In [13]:
# Create a OneHotEncoder for the Attrition column
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False, dtype='int')

# Fit the encoder to the training data
ohe.fit(y_train[["Attrition"]])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_att_encoded = ohe.transform(y_train[["Attrition"]])
y_test_att_encoded = ohe.transform(y_test[["Attrition"]])

# ohe.fit_transform(y_train[["Department"]])
# ohe.fit_transform(y_train[["Department"]])
print([y_train_att_encoded])
print([y_test_att_encoded])

[array([[1, 0],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [0, 1]])]
[array([[1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0]])]

## Create, Compile, and Train the Model

In [14]:
# Find the number of columns in the X training data
#X_train.columns
display(len(X_train.columns))
# Create the input layer

input_layer = layers.Input(shape=(X_train.shape[1],), name='input_features')

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu', name = "shared_layer1")(input_layer)
shared_layer2 = layers.Dense(128, activation='relu', name = "shared_layer2")(shared_layer1)
display(X_train.columns)

10

Index(['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime',
       'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'NumCompaniesWorked'],
      dtype='object')

In [15]:
y_train_att_encoded

array([[1, 0],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [1, 0],
       [0, 1]])

In [16]:
y_train_dep_encoded.size

3306

In [17]:
display(y_train_dep_encoded.shape[1])
display(y_train_att_encoded.shape[1])

3

2

In [18]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer
#department_output = layers.Dense(3, activation='softmax', name='department_output')(shared_layer2)

# pose_dense = layers.Dense(64, activation='relu')(dense_shared)
# pose_output = layers.Dense(len(y_train_pose.columns),
#                            activation='softmax',
#                              name='pose_output')(pose_dense)
#shared_layer2 = layers.Dense(128, activation='relu')(shared_layer1)
department_hidden = layers.Dense(32, activation='relu',name='department_hidden')(shared_layer2)
department_output = layers.Dense(y_train_dep_encoded.shape[1],activation='softmax',name='department_output')(department_hidden)

In [19]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer
# attrition_output = layers.Dense(3, activation='softmax', name='attrition_output')(shared_layer2)
attrition_hidden = layers.Dense(32, activation='relu', name= "attrition_hidden")(shared_layer2)
# attrition_output = layers.Dense(y_train_att_encoded.shape[1],activation='sigmoid',name='attrition_output')(department_dense)
attrition_output = layers.Dense(y_train_att_encoded.shape[1],activation='sigmoid',name='attrition_output')(attrition_hidden)

In [20]:
display(y_train_att_encoded.size)
display(y_train_att_encoded.shape[1])
display(y_train_dep_encoded.shape[1])

2204

2

3

In [21]:
attrition_output

In [22]:
department_output

In [23]:
# Create the model
model = Model(inputs=input_layer, outputs=[
    department_output,
    attrition_output
])

# Compile the model
model.compile(optimizer='adam',
            # loss={'department_output': 'categorical_crossentropy',
            #       'attrition_output': 'binary_crossentropy'
            #      },
            loss={'department_output': 'categorical_crossentropy',
                  'attrition_output': 'categorical_crossentropy'
                 },
            # loss={'department_output': tf.keras.losses.CategoricalCrossentropy(from_logits=False),
            # 'attrition_output': tf.keras.losses.CategoricalCrossentropy(from_logits=False)
            # },
            metrics={'department_output': 'accuracy',
            'attrition_output': 'accuracy'
            })

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_features (InputLayer)   │ (None, 10)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ shared_layer1 (Dense)         │ (None, 64)                │             704 │ input_features[0][0]       │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ shared_layer2 (Dense)         │ (None, 128)               │           8,320 │ shared_layer1[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ department_hidden (Dense)     │ (None, 32)                │           4,128 │ shared_layer2[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ attrition_hidden (Dense)      │ (None, 32)                │           4,128 │ shared_layer2[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ department_output (Dense)     │ (None, 3)                 │              99 │ department_hidden[0][0]    │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ attrition_output (Dense)      │ (None, 2)                 │              66 │ attrition_hidden[0][0]     │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
X_train

,Education,Age,DistanceFromHome,JobSatisfaction,OverTime,StockOptionLevel,WorkLifeBalance,YearsAtCompany,YearsSinceLastPromotion,NumCompaniesWorked
1321,4,47,9,3,0.0,0,3,2,2,4
1091,3,33,25,2,0.0,0,3,5,0,1
985,4,31,22,3,1.0,2,2,10,6,1
455,5,33,1,3,0.0,1,3,6,0,4
952,3,31,1,2,1.0,0,4,3,2,1
...,...,...,...,...,...,...,...,...,...,...
437,1,30,7,2,0.0,0,3,3,1,0
988,3,41,22,4,1.0,2,2,6,3,3
251,4,39,2,3,0.0,0,3,19,11,0
844,3,30,10,3,0.0,1,3,10,1,1
363,3,33,5,3,1.0,0,3,1,0,1

In [25]:
# Train the model

model.fit(
    X_train,
    {
        'department_output': y_train_dep_encoded,
        'attrition_output': y_train_att_encoded
        # 'department_output': department_output,
        # 'attrition_output': attrition_output
        #'department_output': y_df["Department"],
        #'attrition_output': y_df["Attrition"]
    },
    epochs=100,  # You can adjust the number of epochs based on your needs
    batch_size=32,  # You can adjust the batch size based on your available memory
    #validation_split=0.2  # You can specify the validation split if you have a separate validation set
)

Epoch 1/100

ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 2), output.shape=(None, 3)

In [26]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test, {'department_output': y_train_dep_encoded, 'attrition_output': y_train_att_encoded})
test_results

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 368
'y' sizes: 1102, 1102

In [ ]:
# Print the accuracy for both department and attrition

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3.